apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-a-deployment
  labels:
    app: app-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-a
  template:
    metadata:
      labels:
        app: app-a
    spec:
      containers:
      - name: app-a
        image: app-a-image:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
---
kind: Service
apiVersion: v1
metadata:
  name: app-a-service
spec:
  selector:
    app: app-a
  ports:
  - protocol: TCP
    port: 5000
    nodePort: 30001
  type: NodePort